require('lego.options')
require('lego.plugins')
require('lego.mason-config')
require('lego.lsp-clients')
require('lego.telescope')
require('lego.treesitter')
require('lego.comment')
require('lego.keymaps')
require('lego.lualine')

